# Generated by Django 5.0.2 on 2024-03-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeTestCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
