# Generated by Django 5.0.2 on 2024-02-28 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkapp', '0003_product_isbn_product_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='arkapp.courses'),
        ),
    ]
