# Generated by Django 5.0.2 on 2024-03-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkapp', '0004_addquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
